extends SceneTree
## Bake detached source-face samples for worker-side cap burial.
const ROCKS=preload("res://scripts/terrain/field/CliffSlopeRocks.gd")
func _initialize()->void:
 ROCKS.prepare()
 var fronts:="extends RefCounted\n## Generated source-front samples for visible area checks.\nconst POINTS:={\n"
 var text:="extends RefCounted\n## Generated by tests/harness/bake_slope_rock_caps.gd from the fitted native assets.\nconst FACES:={\n"
 for name:String in ROCKS.PIECES:
  if not name.begins_with("face_"):continue
  var piece:Array=ROCKS._pieces[name]
  var faces:PackedVector3Array=piece[0].get_faces()
  var grid:={}
  var bounds:Vector3=ROCKS.PIECES[name][1]
  for vtx:Vector3 in faces:
   var pt:Vector3=piece[1]*vtx
   var key:=Vector2i(roundi(pt.x/bounds.x*24),roundi(pt.y/bounds.y*24))
   if not grid.has(key) or pt.z>(grid[key] as Vector3).z:grid[key]=pt
  fronts+='"%s":[\n'%name
  for point:Vector3 in grid.values():fronts+=v(point)+',\n'
  fronts+='],\n'
  text+='"%s":[\n'%name
  var count:=0
  for i in range(0,faces.size(),3):
   var a:Vector3=piece[1]*faces[i];var b:Vector3=piece[1]*faces[i+1];var c:Vector3=piece[1]*faces[i+2]
   var n:Vector3=(b-a).cross(c-a).normalized()
   if maxf(absf(a.y),maxf(absf(b.y),absf(c.y)))<bounds.y*.38:continue
   text+='[%s,%s,%s,%s],\n'%[v(n),v(a),v(b),v(c)];count+=1
  text+=' ],\n'
  print(name,": ",count)
 text+='}\n'
 var file:=FileAccess.open("res://scripts/terrain/field/CliffSlopeRockCaps.gd",FileAccess.WRITE);file.store_string(text);file.close()
 fronts+="}\n"
 file=FileAccess.open("res://scripts/terrain/field/CliffSlopeRockFronts.gd",FileAccess.WRITE);file.store_string(fronts);file.close();quit()
func v(p:Vector3)->String:return "Vector3(%.7f,%.7f,%.7f)"%[p.x,p.y,p.z]
